FROM 491431825058.dkr.ecr.us-east-1.amazonaws.com/mldemo:python-base-latest

ARG SITE_PKGS_PATH=/var/lang/lib/python3.11s/site-packages

RUN yum install -y git wget unzip gcc
RUN pip3 install pyyaml==5.1 pycocotools tf-models-official

# third party deps
COPY layers/third-party/ml/requirements.txt /tmp
RUN mkdir -p ${SITE_PKGS_PATH} && \
    python -m pip install --upgrade pip && \
    python -m pip install -r /tmp/requirements.txt -t ${SITE_PKGS_PATH} && \
    rm /tmp/requirements.txt

# add models
COPY ../layers/models/mlmodels /opt/mlmodels

ENTRYPOINT ["/lambda-entrypoint.sh"]
